### PR TITLE
Mouse lock

### PR DESCRIPTION
**Pull request by dudeisbrendan03**

### CODE REVIEW

**Comment by dudeisbrendan03** [comment]
Accidentally used my work account for my GitLab, forgot to change over at the start. That's what the `Brendan T D. J` user is

**Comment by mvrozanti** [comment]
looks good

thank you

**Comment by mvrozanti** [comment]
Except I really miss `/hear`. We really need to get pyaudio working again.

**Comment by Dagdelo** [comment]
> Except I really miss `/hear`. We really need to get pyaudio working again.

I'm using [this](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio) pyaudio ported by [Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/). And /hear works fine!

**Comment by dudeisbrendan03** [comment]
I'll take a look

**Comment by dudeisbrendan03** [comment]
@Dagdelo - thanks, that pyAudio module installed fine and didn't spit errors. I can't test it atm, I'm going to make a pull request if you want to try it you can but I think it should work if it originally did anyway.

**Pull request merged**
