### PR TITLE
Starting place for logging

### PR DESCRIPTION
**Pull request by dudeisbrendan03**
# Pull Request Template

## Please follow this format by copying and pasting or otherwise

Describe this request in around 8 words: Logging

_________________

Does this request fix an issue, add a feature or otherwise (what is the purpose of the request): Improves logging

If this is related to an issue, specify the issue in hand: n/a

If this is related to a commit, specify the commit in hand: n/a

If this adds a feature, specify the feature you are adding/improving: Logging
_________________
Give a detailed description of what the PR contains, and the reasoning behind it: Logs to files in `logs/DATE-log.txt`

### CODE REVIEW

**Review by mvrozanti — APPROVED** [review]
Love the templating for PRs
As always, keep up the good work

**Comment by dudeisbrendan03** [comment]
Thanks

**Comment by mvrozanti** [comment]
May I remind that checksum validation should not be necessary if we are installing wheels with `pip install [wheel url]`. It does add a little bloat

**Comment by dudeisbrendan03** [comment]
I'll delete the checksum verifier then merge it then. Is that fine with you @mvrozanti?

**Comment by mvrozanti** [comment]
Sounds great

**Pull request merged**
