### PR TITLE
pyAudio fix (I think)

### PR DESCRIPTION
**Pull request by dudeisbrendan03**
Haven't had time to test. Should work if it originally did. Thanks to @Dagdelo for recommending the module - its a wheel archive that needs installing though

### CODE REVIEW

**Comment by Dagdelo** [comment]
> Oh, have you tested it?

Yeap. Without a input  (recording) device the PyAudio spill a error. Finishing the app.

**Comment by dudeisbrendan03** [comment]
So if you have an input device it works, right? And if so can you give me the error so I can except it, I can't set it all up at the minute. Thanks

**Comment by Dagdelo** [comment]
> So if you have an input device it works, right? And if so can you give me the error so I can except it, I can't set it all up at the minute. Thanks

image

>                 Got message from 400496256: /hear
> 
> 
> Traceback (most recent call last):
>   File "C:\Python37\lib\site-packages\telepot\__init__.py", line 1158, in collector
>     callback(item)
>   File "RATAttack.py", line 331, in handle
>     frames_per_buffer=CHUNK)
>   File "C:\Python37\lib\site-packages\pyaudio.py", line 750, in open
>     stream = Stream(self, *args, **kwargs)
>   File "C:\Python37\lib\site-packages\pyaudio.py", line 441, in __init__
>     self._stream = pa.open(**arguments)
> OSError: [Errno -9996] Invalid input device (no default output device)

**Comment by mvrozanti** [comment]
I think we should stay away of having binaries tracked. Why not use `pip` instead?

**Comment by Dagdelo** [comment]
> I think we should stay away of having binaries tracked. Why not use `pip` instead?

Because the version on the pip is broken :(

**Comment by dudeisbrendan03** [comment]
pyAudio on pip doesn't seem to work, this wheel does. Same with pyHook

**Comment by dudeisbrendan03** [comment]
I'm stopping for now, I'll get to it later. If it doesn't crash when there is no input device and everybody is ok with it then go ahead and pull it. See you guys later! Thanks for the help @Dagdelo!

**Comment by mvrozanti** [comment]
We can add how to install the wheel from url on the README installation section:
`pip install https://download.lfd.uci.edu/pythonlibs/h2ufg7oq/PyAudio-0.2.11-cp37-cp37m-win_amd64.whl`

Checking MD5 checksums is a bit time consuming. Binaries in repos are just shady.

**Comment by dudeisbrendan03** [comment]
Guess so

**Comment by mvrozanti** [comment]
Great work anyways @dudeisbrendan03

**Comment by dudeisbrendan03** [comment]
Should I verify the checksums or just install via pip, I've made a script to verify the checksums.

**Comment by mvrozanti** [comment]
There should be no need for verifying checksums if pip install them from the url. The url is the verification

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dudeisbrendan03** [comment]
k

**Pull request merged**
